environment:
  version_nodejs: "8"
install:
  - ps: Install-Product node $env:version_nodejs x64
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run tslint
  - npm run build
  - npm run coverage
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-report.xml))
on_success:
  - ./node_modules/.bin/codecov
build: off
branches:
  only:
    - master
deploy_script:
  - ps: |
      if ($ENV:APPVEYOR_REPO_TAG_NAME)
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN}`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm publish --access public"
      }
