environment:
  version_nodejs: "8"
install:
  - ps: Install-Product node $env:version_nodejs x64
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run tslint
  - npm run build
  - npm run coverage
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-report.xml))
on_success:
  - ./node_modules/.bin/codecov
build: off
version: "0.1.0-build.{build}"
branches:
  only:
    - master
