environment:
  version_nodejs: "8"
install:
  - ps: Install-Product node $env:version_nodejs x64
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run quality:lint
  - npm run compile
  - npm run test:coverage
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-report.xml))
on_success:
  - ./node_modules/.bin/codecov
build: off
branches:
  only:
    - master
