env:
  global:
    - CC_TEST_REPORTER_ID=890de36877ec510e61f20bbbb15a037035ee2c16e90e500efce6e106fdc0d547
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - greenkeeper-lockfile-update
script:
  - npm install
  - npm run tslint
  - npm run build
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
